from typing import Annotated, TypedDict, List, Any, Dict


def add_messages(existing: List[Any], new: List[Any]) -> List[Any]:
    """Fallback reducer compatible with LangGraph's message accumulator contract."""
    return [*existing, *new]

class AgentState(TypedDict):
    # Standard message history
    messages: Annotated[List, add_messages]
    
    # Research context (Godot/Vulkan docs)
    research_context: str
    
    # Architecture plan (generated by Architect node)
    blueprint: str

    # Planned output file path generated by architect
    target_file: str

    # Code patch payload generated by architect/coder
    code_patch: str
    
    # Tracking current project path
    project_root: str
    
    # Error logs from Godot MCP
    execution_errors: List[str]

    # Reasoning trail and terminal outputs from coder/validator
    agent_reasoning: str
    terminal_history: List[Dict[str, Any]]
    
    # Flag to terminate the loop
    task_complete: bool

    # Track token consumption per cycle (for cost monitoring)
    token_usage: int
