class FastLanguageModel:
    @staticmethod
    def from_pretrained(model_name: str, max_seq_length: int = 2048, load_in_4bit: bool = False): ...

    @staticmethod
    def get_peft_model(model, r: int, target_modules: list, lora_alpha: int, lora_dropout: float, bias: str, use_gradient_checkpointing: bool): ...

    def save_pretrained_gguf(self, model_dir: str, tokenizer, quantization_method: str = "q4_k_m") -> None: ...
